[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  version = "1.1.1"
  name = "github.com/gogo/protobuf"

[[override]]
  version = "1.2.0"
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "github.com/solo-io/solo-kit"
  version = "0.9.0"

[[constraint]]
  name = "github.com/solo-io/go-utils"
  version = "0.8.4"

[[override]]
  name = "k8s.io/kubernetes"
  version = "=v1.13.1"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/helm"
  version = "v2.12.3"

[[constraint]]
  name = "github.com/solo-io/gloo"
  version = "0.13.21"

[[constraint]]
  name = "github.com/solo-io/supergloo"
  version = "0.3.18"

[[constraint]]
  name = "github.com/solo-io/supergloo"
  version = "0.3.17"

[[override]]
  name = "github.com/lyft/protoc-gen-validate"
  version = "0.0.6"
  source = "github.com/envoyproxy/protoc-gen-validate"