apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: glooshot
  name: glooshot
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.glooshot.deployment.replicas }}
  selector:
    matchLabels:
      app: glooshot
  template:
    metadata:
      labels:
        app: glooshot
    spec:
      serviceAccountName: glooshot-serviceaccount
      containers:
      - image: "{{ .Values.glooshot.deployment.image.repository }}:{{ .Values.glooshot.deployment.image.tag }}"
        imagePullPolicy: {{ .Values.glooshot.deployment.image.pullPolicy }}
        name: glooshot
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      {{- if .Values.glooshot.deployment.image.pullSecret }}
      imagePullSecrets:
      - name: solo-io-docker-secret
      {{- end -}}

