{{- if .Values.rbac.create }}

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: glooshot-role
    namespace: {{ .Release.Namespace }}
    labels:
        app: glooshot
        glooshot: rbac
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "create"]
- apiGroups: ["glooshot.solo.io"]
  resources: ["experiments"]
  verbs: ["*"]

{{- end -}}
